MODNAME := pwblkdev
# modules to be built
obj-m := ${MODNAME}.o

# object files for a module
#${MODNAME}-y := src/devicesupport.o src/init.o src/iosupport.o src/queuesupport.o

# object files for a module
${MODNAME}-objs := src/devicesupport.o src/init.o src/iosupport.o src/queuesupport.o
